### ISSUE TITLE
object model error when re-trying resque job

### ISSUE THREAD

**Issue by dunn** [ucsblibrary/alexandria#136]
I tried to re-run a failed Resque job for a newspaper, and the new job had a malformed Model:
```
Worker
    adrlrails:5022 on ingest at 12 minutes ago
    Retry or Remove
Class
    Importer::Factory::Job 
Arguments

    ---
    model: Elgaucho19430909.Pdf
    attrs:
      accession_number:
      - LB3621.65 .D35 19660329
      title:
      - El Gaucho, March 29, 1966
      issuing_body:
      - hash: 
        object: 
        value: http://id.loc.gov/authorities/names/n80126303
      extent:
      - 24 pages
      description:
      - Volume 46, Special Supplement. Special Supplement on the University Center.
      language:
      - hash: 
        object: 
        value: http://id.loc.gov/vocabulary/iso639-2/eng
      note:
      - Publication frequency varies.
      - 'Issued by the College under its various names: 1934- Santa Barbara State Teachers
        College; 1935- Santa Barbara State College; 1944- Santa Barbara College; 1958-
        University of California, Santa Barbara.'
      - Absorbed El Gauchito in 1966 which then assumed numbering of El Gaucho and continued
        publication as Summer El Gaucho from 1966-1969.
      - 'Previous title: Roadrunner (Santa Barbara, Calif. : 1930).'
      - 'Later title: UCSB daily Nexus.'
      place_of_publication:
      - "[Santa Barbara, Calif.]"
      publisher:
      - "[Associated Students of Univ. of California, Santa Barbara]"
      issued_attributes:
      - start:
        - '1966-03-29'
        label:
        - March 29, 1966
      lc_subject:
      - hash: 
        object: 
        value: http://id.loc.gov/authorities/subjects/sh85028351
      - hash: 
        object: 
        value: http://id.loc.gov/authorities/names/n80126303
      location:
      - hash: 
        object: 
        value: http://id.loc.gov/authorities/names/n79081574
      - hash: 
        object: 
        value: http://id.loc.gov/authorities/names/n79041717
      form_of_work:
      - hash: 
        object: 
        value: http://vocab.getty.edu/aat/300026656
      - hash: 
        object: 
        value: http://vocab.getty.edu/aat/300026657
      work_type:
      - hash: 
        object: 
        value: http://id.loc.gov/vocabulary/resourceTypes/txt
      digital_origin:
      - reformatted digital
      collection:
        id: lb362165D35
        accession_number:
        - LB3621.65 .D35
        title:
        - University of California, Santa Barbara Daily Nexus and antecedent newspapers
      series_name:
      - El Gaucho
      institution:
      - hash: 
        object: 
        value: http://id.loc.gov/vocabulary/organizations/cusb
      sub_location:
      - Department of Special Research Collections
      copyright_status:
      - hash: 
        object: 
        value: http://id.loc.gov/vocabulary/preservation/copyrightStatus/pub
      license:
      - hash: 
        object: 
        value: http://rightsstatements.org/vocab/NoC-US/1.0/
      files:
      - "/special/vendor_digital_projects/UARCH_backstage/UCSB_012/PDFs/elgaucho_19660329_unisupp.pdf"
      admin_policy_id: authorities/policies/public
    files:
    - "/opt/ingest/special/vendor_digital_projects/UARCH_backstage/UCSB_012/PDFs/elgaucho_19660329_unisupp.pdf"

Exception
    NameError
Error
    wrong constant name Elgaucho19430909.PdfFactory

    /opt/alexandria/releases/20180124215904/lib/importer/factory.rb:21:in `const_get'
    /opt/alexandria/releases/20180124215904/lib/importer/factory.rb:21:in `for'
    /opt/alexandria/releases/20180124215904/lib/importer/factory/job.rb:9:in `perform'
```
I couldn't find the original job (the queue is very large right now).

**Comment by dunn** [comment]
This was an error in the metadata per @chrissyrissmeyer
